const sampleStudents = [
    { id: "hs_1", name: "TRỌNG TÍN", seatId: "seat-c1-r2-s1" },
    { id: "hs_2", name: "NGHIỆP TƯỜNG", seatId: "seat-c1-r2-s2" },
    { id: "hs_3", name: "HIỀN CHI", seatId: "seat-c1-r3-s1" },
    { id: "hs_4", name: "KHÁNH TRÂM", seatId: "seat-c1-r3-s2" },
    { id: "hs_5", name: "KHÁNH NHƯ", seatId: "seat-c1-r4-s1" },
    { id: "hs_6", name: "CÁT TƯỜNG", seatId: "seat-c1-r4-s2" },
    { id: "hs_7", name: "NGỌC HUYỀN", seatId: "seat-c1-r5-s1" },
    { id: "hs_8", name: "HOÀNG KHƯƠNG", seatId: "seat-c1-r5-s2" },
    { id: "hs_9", name: "XUÂN ĐỨC", seatId: "seat-c1-r6-s1" },
    { id: "hs_10", name: "MINH HÀ", seatId: "seat-c1-r6-s2" },

    { id: "hs_11", name: "DIỆU HIỀN", seatId: "seat-c2-r1-s1" },
    { id: "hs_12", name: "HẢI YẾN", seatId: "seat-c2-r1-s2" },
    { id: "hs_13", name: "QUỐC MINH", role: "(LPHT)", seatId: "seat-c2-r2-s1" },
    { id: "hs_14", name: "XUÂN PHÚC", seatId: "seat-c2-r2-s2" },
    { id: "hs_15", name: "UYÊN NHI", role: "(LPVTM)", seatId: "seat-c2-r3-s1" },
    { id: "hs_16", name: "PHẠM BẢO NGỌC", seatId: "seat-c2-r3-s2" },
    { id: "hs_17", name: "MINH QUÂN", seatId: "seat-c2-r4-s1" },
    { id: "hs_18", name: "VIỆT HÀ", seatId: "seat-c2-r4-s2" },
    { id: "hs_19", name: "TRẦN QUỲNH ANH", seatId: "seat-c2-r5-s1" },
    { id: "hs_20", name: "NGỌC TRÂN", role: "(BTCĐ)", seatId: "seat-c2-r5-s2" },
    { id: "hs_21", name: "THIÊN Ý", seatId: "seat-c2-r6-s1" },
    { id: "hs_22", name: "HOÀNG HUY", seatId: "seat-c2-r6-s2" },

    { id: "hs_23", name: "HOÀNG MINH", seatId: "seat-c3-r1-s1" },
    { id: "hs_24", name: "KHÁNH QUÂN", role: "(LỚP TRƯỞNG)", seatId: "seat-c3-r1-s2" },
    { id: "hs_25", name: "ANH THƯ", seatId: "seat-c3-r2-s1" },
    { id: "hs_26", name: "BÁCH ĐẠT", seatId: "seat-c3-r2-s2" },
    { id: "hs_27", name: "GIA HUY", seatId: "seat-c3-r3-s1" },
    { id: "hs_28", name: "LÊ NGUYỄN", seatId: "seat-c3-r3-s2" },
    { id: "hs_29", name: "ĐOÀN BẢO NGỌC", seatId: "seat-c3-r4-s1" },
    { id: "hs_30", name: "THIÊN KIM", seatId: "seat-c3-r4-s2" },
    { id: "hs_31", name: "NHƯ Ý", seatId: "seat-c3-r5-s1" },
    { id: "hs_32", name: "THU TRÂM", seatId: "seat-c3-r5-s2" },
    { id: "hs_33", name: "VĂN KHANG", seatId: "seat-c3-r6-s1" },
    { id: "hs_34", name: "NGUYỄN QUỲNH ANH", seatId: "seat-c3-r6-s2" },

    { id: "hs_35", name: "NHẬT MINH", seatId: "seat-c4-r2-s1" },
    { id: "hs_36", name: "TUẤN KIỆT", seatId: "seat-c4-r2-s2" },
    { id: "hs_37", name: "NHẬT HUY", seatId: "seat-c4-r3-s1" },
    // seat-c4-r3-s2 is empty
    { id: "hs_38", name: "DUY ĐẠT", seatId: "seat-c4-r4-s1" },
    { id: "hs_39", name: "TƯƠNG PHỐ", seatId: "seat-c4-r4-s2" },
    { id: "hs_40", name: "HOÀNG CHÂU", seatId: "seat-c4-r5-s1" },
    { id: "hs_41", name: "THIÊN HÀ", seatId: "seat-c4-r5-s2" },
    { id: "hs_42", name: "KỲ SƠN", seatId: "seat-c4-r6-s1" },
    { id: "hs_43", name: "HUY HOÀNG", seatId: "seat-c4-r6-s2" }
];
