insert into public.classroom_students (id, classroom_id, name, role, seat_id, is_locked)
values
  ('hs_1', 'lop-x6', 'TRỌNG TÍN', '', 'seat-c1-r2-s1', false),
  ('hs_2', 'lop-x6', 'NGHIỆP TƯỜNG', '', 'seat-c1-r2-s2', false),
  ('hs_3', 'lop-x6', 'HIỀN CHI', '', 'seat-c1-r3-s1', false),
  ('hs_4', 'lop-x6', 'KHÁNH TRÂM', '', 'seat-c1-r3-s2', false),
  ('hs_5', 'lop-x6', 'KHÁNH NHƯ', '', 'seat-c1-r4-s1', false),
  ('hs_6', 'lop-x6', 'CÁT TƯỜNG', '', 'seat-c1-r4-s2', false),
  ('hs_7', 'lop-x6', 'NGỌC HUYỀN', '', 'seat-c1-r5-s1', false),
  ('hs_8', 'lop-x6', 'HOÀNG KHƯƠNG', '', 'seat-c1-r5-s2', false),
  ('hs_9', 'lop-x6', 'XUÂN ĐỨC', '', 'seat-c1-r6-s1', false),
  ('hs_10', 'lop-x6', 'MINH HÀ', '', 'seat-c1-r6-s2', false),
  ('hs_11', 'lop-x6', 'DIỆU HIỀN', '', 'seat-c2-r1-s1', false),
  ('hs_12', 'lop-x6', 'HẢI YẾN', '', 'seat-c2-r1-s2', false),
  ('hs_13', 'lop-x6', 'QUỐC MINH', '(LPHT)', 'seat-c2-r2-s1', false),
  ('hs_14', 'lop-x6', 'XUÂN PHÚC', '', 'seat-c2-r2-s2', false),
  ('hs_15', 'lop-x6', 'UYÊN NHI', '(LPVTM)', 'seat-c2-r3-s1', false),
  ('hs_16', 'lop-x6', 'PHẠM BẢO NGỌC', '', 'seat-c2-r3-s2', false),
  ('hs_17', 'lop-x6', 'MINH QUÂN', '', 'seat-c2-r4-s1', false),
  ('hs_18', 'lop-x6', 'VIỆT HÀ', '', 'seat-c2-r4-s2', false),
  ('hs_19', 'lop-x6', 'TRẦN QUỲNH ANH', '', 'seat-c2-r5-s1', false),
  ('hs_20', 'lop-x6', 'NGỌC TRÂN', '(BTCĐ)', 'seat-c2-r5-s2', false),
  ('hs_21', 'lop-x6', 'THIÊN Ý', '', 'seat-c2-r6-s1', false),
  ('hs_22', 'lop-x6', 'HOÀNG HUY', '', 'seat-c2-r6-s2', false),
  ('hs_23', 'lop-x6', 'HOÀNG MINH', '', 'seat-c3-r1-s1', false),
  ('hs_24', 'lop-x6', 'KHÁNH QUÂN', '(LỚP TRƯỞNG)', 'seat-c3-r1-s2', false),
  ('hs_25', 'lop-x6', 'ANH THƯ', '', 'seat-c3-r2-s1', false),
  ('hs_26', 'lop-x6', 'BÁCH ĐẠT', '', 'seat-c3-r2-s2', false),
  ('hs_27', 'lop-x6', 'GIA HUY', '', 'seat-c3-r3-s1', false),
  ('hs_28', 'lop-x6', 'LÊ NGUYỄN', '', 'seat-c3-r3-s2', false),
  ('hs_29', 'lop-x6', 'ĐOÀN BẢO NGỌC', '', 'seat-c3-r4-s1', false),
  ('hs_30', 'lop-x6', 'THIÊN KIM', '', 'seat-c3-r4-s2', false),
  ('hs_31', 'lop-x6', 'NHƯ Ý', '', 'seat-c3-r5-s1', false),
  ('hs_32', 'lop-x6', 'THU TRÂM', '', 'seat-c3-r5-s2', false),
  ('hs_33', 'lop-x6', 'VĂN KHANG', '', 'seat-c3-r6-s1', false),
  ('hs_34', 'lop-x6', 'NGUYỄN QUỲNH ANH', '', 'seat-c3-r6-s2', false),
  ('hs_35', 'lop-x6', 'NHẬT MINH', '', 'seat-c4-r2-s1', false),
  ('hs_36', 'lop-x6', 'TUẤN KIỆT', '', 'seat-c4-r2-s2', false),
  ('hs_37', 'lop-x6', 'NHẬT HUY', '', 'seat-c4-r3-s1', false),
  ('hs_38', 'lop-x6', 'DUY ĐẠT', '', 'seat-c4-r4-s1', false),
  ('hs_39', 'lop-x6', 'TƯƠNG PHỐ', '', 'seat-c4-r4-s2', false),
  ('hs_40', 'lop-x6', 'HOÀNG CHÂU', '', 'seat-c4-r5-s1', false),
  ('hs_41', 'lop-x6', 'THIÊN HÀ', '', 'seat-c4-r5-s2', false),
  ('hs_42', 'lop-x6', 'KỲ SƠN', '', 'seat-c4-r6-s1', false),
  ('hs_43', 'lop-x6', 'HUY HOÀNG', '', 'seat-c4-r6-s2', false)
on conflict (id) do nothing;
